### ISSUE TITLE
searchForLocations doesn't return `name` on Android

### ISSUE THREAD

**Issue by IjzerenHein** [kiwicom/react-native-reverse-geocode#7] opened 2019-03-06 13:06 UTC
Hi, first of all, thanks for this great package! 👍 

On iOS I'm getting a nice `name` when I call `searchForLocations`, however on Android I'm always getting `null` back. Is this by design, or did I misconfigure something?

![image](https://user-images.githubusercontent.com/6184593/53883335-fed0cb80-4018-11e9-87f5-815fa3d7886f.png)

cheers

**Comment by tbergq** [comment] 2019-03-06 13:39
Hi, currently it is by design, but we could definitely improve it. We will get to this when possible. I can not promise when that will be though. 

The solution should be calling [this method](https://developer.android.com/reference/android/location/Address.html#getFeatureName())

Please feel free to submit a PR 🙂

**Comment by IjzerenHein** [comment] 2019-03-06 13:42
Alright, thanks for getting back and that info.
I'll try to submit a PR 👍

**Comment by IjzerenHein** [comment] 2019-03-06 13:53
Fun, this will be my first Kotlin contribution :)

**Comment by tbergq** [comment] 2019-03-06 14:44
Thanks for your help @IjzerenHein. Your commit has been merged, and a new version `0.0.4` has been pushed to npm.

**Closed by tbergq** 2019-03-06 14:44 UTC
Labels: good first issue, help wanted

**Comment by IjzerenHein** [comment] 2019-03-06 14:56
Cool, thanks @tbergq !

I'm almost done with the next PR, which filters out the duplicates on Android as well
